image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - cd backend
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

#test:
#  stage: test
#  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
#  dependencies:
#    - build
#  before_script:
#    - cd backend
#    - npm install
#  script:
#    - npm run test
#  cache:
#    paths:
#      - ./backend/coverage
#  artifacts:
#    paths:
#      - ./backend/coverage
#    when: always
#    reports:
#      junit:
#        - junit.xml
#      coverage_report:
#        coverage_format: cobertura
#        path: backend/coverage/cobertura-coverage.xml

pages:
  stage: deploy
  dependencies:
    - test
  script:
      - mkdir .public
      - cp -r coverage/* .public
      - mv .public .public
  artifacts:
    paths:
      - public
  only:
    - master