/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as RegistrationVeterinarypracticeRouteImport } from './routes/registration/veterinarypractice'
import { Route as RegistrationVerifyEmailRouteImport } from './routes/registration/verify-email'
import { Route as RegistrationPersonRouteImport } from './routes/registration/person'
import { Route as PracticesFavoritesRouteImport } from './routes/practices/favorites'
import { Route as PracticesPracticeIdRouteImport } from './routes/practices/$practiceId'
import { Route as PasswordResetRequestRouteImport } from './routes/password-reset/request'
import { Route as BookingConfirmationRouteImport } from './routes/booking/confirmation'
import { Route as BookingAppointmentIdRouteImport } from './routes/booking/$appointmentId'
import { Route as AppointmentsCreateRouteImport } from './routes/appointments/create'
import { Route as RegistrationEmailConfirmationEmailVerifyCodeRouteImport } from './routes/registration/email-confirmation/$emailVerifyCode'
import { Route as PasswordResetConfirmTokenRouteImport } from './routes/password-reset/confirm.$token'
import { Route as AppointmentsAppointmentIdRescheduleRouteImport } from './routes/appointments/$appointmentId/reschedule'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationVeterinarypracticeRoute =
  RegistrationVeterinarypracticeRouteImport.update({
    id: '/registration/veterinarypractice',
    path: '/registration/veterinarypractice',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistrationVerifyEmailRoute = RegistrationVerifyEmailRouteImport.update({
  id: '/registration/verify-email',
  path: '/registration/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationPersonRoute = RegistrationPersonRouteImport.update({
  id: '/registration/person',
  path: '/registration/person',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesFavoritesRoute = PracticesFavoritesRouteImport.update({
  id: '/practices/favorites',
  path: '/practices/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesPracticeIdRoute = PracticesPracticeIdRouteImport.update({
  id: '/practices/$practiceId',
  path: '/practices/$practiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRequestRoute = PasswordResetRequestRouteImport.update({
  id: '/password-reset/request',
  path: '/password-reset/request',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingAppointmentIdRoute = BookingAppointmentIdRouteImport.update({
  id: '/booking/$appointmentId',
  path: '/booking/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: '/appointments/create',
  path: '/appointments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationEmailConfirmationEmailVerifyCodeRoute =
  RegistrationEmailConfirmationEmailVerifyCodeRouteImport.update({
    id: '/registration/email-confirmation/$emailVerifyCode',
    path: '/registration/email-confirmation/$emailVerifyCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const PasswordResetConfirmTokenRoute =
  PasswordResetConfirmTokenRouteImport.update({
    id: '/password-reset/confirm/$token',
    path: '/password-reset/confirm/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsAppointmentIdRescheduleRoute =
  AppointmentsAppointmentIdRescheduleRouteImport.update({
    id: '/appointments/$appointmentId/reschedule',
    path: '/appointments/$appointmentId/reschedule',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/booking/$appointmentId': typeof BookingAppointmentIdRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/practices/$practiceId': typeof PracticesPracticeIdRoute
  '/practices/favorites': typeof PracticesFavoritesRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/verify-email': typeof RegistrationVerifyEmailRoute
  '/registration/veterinarypractice': typeof RegistrationVeterinarypracticeRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/appointments/$appointmentId/reschedule': typeof AppointmentsAppointmentIdRescheduleRoute
  '/password-reset/confirm/$token': typeof PasswordResetConfirmTokenRoute
  '/registration/email-confirmation/$emailVerifyCode': typeof RegistrationEmailConfirmationEmailVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/booking/$appointmentId': typeof BookingAppointmentIdRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/practices/$practiceId': typeof PracticesPracticeIdRoute
  '/practices/favorites': typeof PracticesFavoritesRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/verify-email': typeof RegistrationVerifyEmailRoute
  '/registration/veterinarypractice': typeof RegistrationVeterinarypracticeRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/appointments/$appointmentId/reschedule': typeof AppointmentsAppointmentIdRescheduleRoute
  '/password-reset/confirm/$token': typeof PasswordResetConfirmTokenRoute
  '/registration/email-confirmation/$emailVerifyCode': typeof RegistrationEmailConfirmationEmailVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animals': typeof AnimalsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profil': typeof ProfilRoute
  '/search': typeof SearchRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/booking/$appointmentId': typeof BookingAppointmentIdRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/practices/$practiceId': typeof PracticesPracticeIdRoute
  '/practices/favorites': typeof PracticesFavoritesRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/verify-email': typeof RegistrationVerifyEmailRoute
  '/registration/veterinarypractice': typeof RegistrationVeterinarypracticeRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/appointments/$appointmentId/reschedule': typeof AppointmentsAppointmentIdRescheduleRoute
  '/password-reset/confirm/$token': typeof PasswordResetConfirmTokenRoute
  '/registration/email-confirmation/$emailVerifyCode': typeof RegistrationEmailConfirmationEmailVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animals'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/search'
    | '/appointments/create'
    | '/booking/$appointmentId'
    | '/booking/confirmation'
    | '/password-reset/request'
    | '/practices/$practiceId'
    | '/practices/favorites'
    | '/registration/person'
    | '/registration/verify-email'
    | '/registration/veterinarypractice'
    | '/appointments'
    | '/appointments/$appointmentId/reschedule'
    | '/password-reset/confirm/$token'
    | '/registration/email-confirmation/$emailVerifyCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animals'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/search'
    | '/appointments/create'
    | '/booking/$appointmentId'
    | '/booking/confirmation'
    | '/password-reset/request'
    | '/practices/$practiceId'
    | '/practices/favorites'
    | '/registration/person'
    | '/registration/verify-email'
    | '/registration/veterinarypractice'
    | '/appointments'
    | '/appointments/$appointmentId/reschedule'
    | '/password-reset/confirm/$token'
    | '/registration/email-confirmation/$emailVerifyCode'
  id:
    | '__root__'
    | '/'
    | '/animals'
    | '/dashboard'
    | '/login'
    | '/profil'
    | '/search'
    | '/appointments/create'
    | '/booking/$appointmentId'
    | '/booking/confirmation'
    | '/password-reset/request'
    | '/practices/$practiceId'
    | '/practices/favorites'
    | '/registration/person'
    | '/registration/verify-email'
    | '/registration/veterinarypractice'
    | '/appointments/'
    | '/appointments/$appointmentId/reschedule'
    | '/password-reset/confirm/$token'
    | '/registration/email-confirmation/$emailVerifyCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimalsRoute: typeof AnimalsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfilRoute: typeof ProfilRoute
  SearchRoute: typeof SearchRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  BookingAppointmentIdRoute: typeof BookingAppointmentIdRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  PasswordResetRequestRoute: typeof PasswordResetRequestRoute
  PracticesPracticeIdRoute: typeof PracticesPracticeIdRoute
  PracticesFavoritesRoute: typeof PracticesFavoritesRoute
  RegistrationPersonRoute: typeof RegistrationPersonRoute
  RegistrationVerifyEmailRoute: typeof RegistrationVerifyEmailRoute
  RegistrationVeterinarypracticeRoute: typeof RegistrationVeterinarypracticeRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  AppointmentsAppointmentIdRescheduleRoute: typeof AppointmentsAppointmentIdRescheduleRoute
  PasswordResetConfirmTokenRoute: typeof PasswordResetConfirmTokenRoute
  RegistrationEmailConfirmationEmailVerifyCodeRoute: typeof RegistrationEmailConfirmationEmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/veterinarypractice': {
      id: '/registration/veterinarypractice'
      path: '/registration/veterinarypractice'
      fullPath: '/registration/veterinarypractice'
      preLoaderRoute: typeof RegistrationVeterinarypracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/verify-email': {
      id: '/registration/verify-email'
      path: '/registration/verify-email'
      fullPath: '/registration/verify-email'
      preLoaderRoute: typeof RegistrationVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/person': {
      id: '/registration/person'
      path: '/registration/person'
      fullPath: '/registration/person'
      preLoaderRoute: typeof RegistrationPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/favorites': {
      id: '/practices/favorites'
      path: '/practices/favorites'
      fullPath: '/practices/favorites'
      preLoaderRoute: typeof PracticesFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/$practiceId': {
      id: '/practices/$practiceId'
      path: '/practices/$practiceId'
      fullPath: '/practices/$practiceId'
      preLoaderRoute: typeof PracticesPracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/request': {
      id: '/password-reset/request'
      path: '/password-reset/request'
      fullPath: '/password-reset/request'
      preLoaderRoute: typeof PasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$appointmentId': {
      id: '/booking/$appointmentId'
      path: '/booking/$appointmentId'
      fullPath: '/booking/$appointmentId'
      preLoaderRoute: typeof BookingAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/create': {
      id: '/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/email-confirmation/$emailVerifyCode': {
      id: '/registration/email-confirmation/$emailVerifyCode'
      path: '/registration/email-confirmation/$emailVerifyCode'
      fullPath: '/registration/email-confirmation/$emailVerifyCode'
      preLoaderRoute: typeof RegistrationEmailConfirmationEmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/confirm/$token': {
      id: '/password-reset/confirm/$token'
      path: '/password-reset/confirm/$token'
      fullPath: '/password-reset/confirm/$token'
      preLoaderRoute: typeof PasswordResetConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId/reschedule': {
      id: '/appointments/$appointmentId/reschedule'
      path: '/appointments/$appointmentId/reschedule'
      fullPath: '/appointments/$appointmentId/reschedule'
      preLoaderRoute: typeof AppointmentsAppointmentIdRescheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimalsRoute: AnimalsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfilRoute: ProfilRoute,
  SearchRoute: SearchRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  BookingAppointmentIdRoute: BookingAppointmentIdRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  PasswordResetRequestRoute: PasswordResetRequestRoute,
  PracticesPracticeIdRoute: PracticesPracticeIdRoute,
  PracticesFavoritesRoute: PracticesFavoritesRoute,
  RegistrationPersonRoute: RegistrationPersonRoute,
  RegistrationVerifyEmailRoute: RegistrationVerifyEmailRoute,
  RegistrationVeterinarypracticeRoute: RegistrationVeterinarypracticeRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  AppointmentsAppointmentIdRescheduleRoute:
    AppointmentsAppointmentIdRescheduleRoute,
  PasswordResetConfirmTokenRoute: PasswordResetConfirmTokenRoute,
  RegistrationEmailConfirmationEmailVerifyCodeRoute:
    RegistrationEmailConfirmationEmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
