/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationVeterinaryRouteImport } from './routes/registration/veterinary'
import { Route as RegistrationPersonRouteImport } from './routes/registration/person'
import { Route as PraxenPraxisIdIndexRouteImport } from './routes/praxen/$praxisId/index'
import { Route as PraxenPraxisIdBookingTerminIdRouteImport } from './routes/praxen/$praxisId/booking/$terminId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationVeterinaryRoute = RegistrationVeterinaryRouteImport.update({
  id: '/registration/veterinary',
  path: '/registration/veterinary',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationPersonRoute = RegistrationPersonRouteImport.update({
  id: '/registration/person',
  path: '/registration/person',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxenPraxisIdIndexRoute = PraxenPraxisIdIndexRouteImport.update({
  id: '/praxen/$praxisId/',
  path: '/praxen/$praxisId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxenPraxisIdBookingTerminIdRoute =
  PraxenPraxisIdBookingTerminIdRouteImport.update({
    id: '/praxen/$praxisId/booking/$terminId',
    path: '/praxen/$praxisId/booking/$terminId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/veterinary': typeof RegistrationVeterinaryRoute
  '/praxen/$praxisId': typeof PraxenPraxisIdIndexRoute
  '/praxen/$praxisId/booking/$terminId': typeof PraxenPraxisIdBookingTerminIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/veterinary': typeof RegistrationVeterinaryRoute
  '/praxen/$praxisId': typeof PraxenPraxisIdIndexRoute
  '/praxen/$praxisId/booking/$terminId': typeof PraxenPraxisIdBookingTerminIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/registration/person': typeof RegistrationPersonRoute
  '/registration/veterinary': typeof RegistrationVeterinaryRoute
  '/praxen/$praxisId/': typeof PraxenPraxisIdIndexRoute
  '/praxen/$praxisId/booking/$terminId': typeof PraxenPraxisIdBookingTerminIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/login'
    | '/search'
    | '/registration/person'
    | '/registration/veterinary'
    | '/praxen/$praxisId'
    | '/praxen/$praxisId/booking/$terminId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/login'
    | '/search'
    | '/registration/person'
    | '/registration/veterinary'
    | '/praxen/$praxisId'
    | '/praxen/$praxisId/booking/$terminId'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/login'
    | '/search'
    | '/registration/person'
    | '/registration/veterinary'
    | '/praxen/$praxisId/'
    | '/praxen/$praxisId/booking/$terminId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  RegistrationPersonRoute: typeof RegistrationPersonRoute
  RegistrationVeterinaryRoute: typeof RegistrationVeterinaryRoute
  PraxenPraxisIdIndexRoute: typeof PraxenPraxisIdIndexRoute
  PraxenPraxisIdBookingTerminIdRoute: typeof PraxenPraxisIdBookingTerminIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/veterinary': {
      id: '/registration/veterinary'
      path: '/registration/veterinary'
      fullPath: '/registration/veterinary'
      preLoaderRoute: typeof RegistrationVeterinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/person': {
      id: '/registration/person'
      path: '/registration/person'
      fullPath: '/registration/person'
      preLoaderRoute: typeof RegistrationPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxen/$praxisId/': {
      id: '/praxen/$praxisId/'
      path: '/praxen/$praxisId'
      fullPath: '/praxen/$praxisId'
      preLoaderRoute: typeof PraxenPraxisIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxen/$praxisId/booking/$terminId': {
      id: '/praxen/$praxisId/booking/$terminId'
      path: '/praxen/$praxisId/booking/$terminId'
      fullPath: '/praxen/$praxisId/booking/$terminId'
      preLoaderRoute: typeof PraxenPraxisIdBookingTerminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  RegistrationPersonRoute: RegistrationPersonRoute,
  RegistrationVeterinaryRoute: RegistrationVeterinaryRoute,
  PraxenPraxisIdIndexRoute: PraxenPraxisIdIndexRoute,
  PraxenPraxisIdBookingTerminIdRoute: PraxenPraxisIdBookingTerminIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
